# Generated by Django 3.1.6 on 2021-02-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rice_buy_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True, verbose_name='日期')),
                ('order_amount', models.IntegerField(max_length=8, verbose_name='数量（斤)')),
                ('weight_price', models.FloatField(max_length=8, verbose_name='单价')),
                ('order_price', models.FloatField(max_length=8, verbose_name='进货单价')),
                ('total_amount', models.FloatField(max_length=64, verbose_name='总计费用')),
            ],
        ),
    ]
