# Generated by Django 3.1.6 on 2021-02-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rice_buy_order',
            name='get_rice_ratio',
            field=models.CharField(choices=[('HALF', 'half'), ('THREE', 'three')], default='HALF', max_length=32),
        ),
        migrations.AlterField(
            model_name='rice_buy_order',
            name='order_amount',
            field=models.IntegerField(verbose_name='数量（斤)'),
        ),
        migrations.AlterField(
            model_name='rice_buy_order',
            name='weight_price',
            field=models.FloatField(verbose_name='单价'),
        ),
    ]
