# Generated by Django 3.1.6 on 2021-02-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rice', '0004_auto_20210208_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rice_sell_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('buyer', models.CharField(max_length=8, verbose_name='购买人')),
                ('delivery', models.CharField(max_length=8, verbose_name='收货人')),
                ('phone', models.CharField(max_length=16, verbose_name='收货人电话')),
                ('add', models.CharField(max_length=32, verbose_name='收货地址')),
                ('amount', models.IntegerField(verbose_name='数量(斤)')),
                ('price', models.FloatField(verbose_name='单价(元)')),
                ('delivery_fee', models.FloatField(verbose_name='运费(元/斤)')),
                ('get_rice_ratio', models.CharField(choices=[('HALF', '5:5'), ('FOUR', '4:6'), ('THREE', '3:7')], default='HALF', max_length=32, verbose_name='大米比例')),
                ('get_package', models.CharField(choices=[('GOLDEN', '金包装'), ('SILVER', '银包装'), ('NORMAL', '牛皮纸')], default='NORMAL', max_length=32, verbose_name='包装种类')),
                ('package', models.FloatField(verbose_name='件数(个)')),
                ('delivery_co', models.CharField(max_length=8, verbose_name='发货物流')),
                ('sign_time', models.DateField(verbose_name='签收日期')),
                ('get_pay_status', models.CharField(choices=[('PAIED', '已付款'), ('UNPAY', '未付款')], default='UNPAY', max_length=32, verbose_name='付款状态')),
                ('mark', models.CharField(max_length=32, verbose_name='备注')),
            ],
        ),
    ]
