# Generated by Django 3.1.6 on 2021-02-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rice', '0007_auto_20210208_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rice_sell_order',
            name='amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='数量(斤)'),
        ),
        migrations.AlterField(
            model_name='rice_sell_order',
            name='delivery_fee',
            field=models.FloatField(blank=True, default=0, verbose_name='运费(元/斤)'),
        ),
        migrations.AlterField(
            model_name='rice_sell_order',
            name='price',
            field=models.FloatField(blank=True, default=0, verbose_name='单价(元)'),
        ),
    ]
