# Generated by Django 3.1.6 on 2021-02-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rice', '0008_auto_20210208_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rice_sell_order',
            name='package',
            field=models.FloatField(blank=True, default=0, verbose_name='件数(个)'),
        ),
    ]
