# Generated by Django 3.1.6 on 2021-02-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rice', '0009_auto_20210208_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rice_sell_order',
            name='sign_time',
            field=models.DateField(auto_now_add=True, verbose_name='签收日期'),
        ),
    ]
