# Generated by Django 3.1.6 on 2021-02-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rice', '0010_auto_20210208_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rice_sell_order',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='日期'),
        ),
    ]
