# Generated by Django 3.1.6 on 2021-02-09 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rice', '0012_auto_20210208_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rice_buy_order',
            old_name='date',
            new_name='put_date',
        ),
        migrations.RenameField(
            model_name='rice_sell_order',
            old_name='date',
            new_name='put_date',
        ),
    ]
