# Generated by Django 3.1.6 on 2021-02-09 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rice', '0013_auto_20210209_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rice_sell_order',
            old_name='amount',
            new_name='order_amount',
        ),
        migrations.RenameField(
            model_name='rice_sell_order',
            old_name='price',
            new_name='order_price',
        ),
    ]
