# Generated by Django 3.1.6 on 2021-02-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rice', '0014_auto_20210209_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rice_Bought_Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_month', models.CharField(blank=True, max_length=8, verbose_name='月份')),
                ('rice_ratio', models.CharField(blank=True, max_length=8, verbose_name='大米比例')),
                ('package_type', models.CharField(blank=True, max_length=8, verbose_name='包装')),
                ('rice_money', models.FloatField(blank=True, default=0, verbose_name='大米费用小计')),
                ('lux_money', models.FloatField(blank=True, default=0, verbose_name='精装盒小计')),
                ('big_money', models.FloatField(blank=True, default=0, verbose_name='大包费用小计')),
                ('total_money', models.FloatField(blank=True, default=0, verbose_name='成本总额')),
            ],
            options={
                'verbose_name': '进货报表',
                'verbose_name_plural': '进货报表',
            },
        ),
    ]
