# Generated by Django 3.1.6 on 2021-02-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rice', '0015_rice_bought_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rice_Stock_Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(blank=True, max_length=9, verbose_name='包装种类')),
                ('stock_amount', models.IntegerField(default=0, verbose_name='库存剩余')),
            ],
            options={
                'verbose_name': '库存盘点',
                'verbose_name_plural': '库存盘点',
            },
        ),
    ]
