# Generated by Django 3.1.6 on 2021-02-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rice', '0016_rice_stock_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='rice_stock_check',
            name='stock_rice_ratio',
            field=models.CharField(blank=True, max_length=8, verbose_name='大米比例'),
        ),
    ]
