# Generated by Django 3.1.6 on 2021-02-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rice', '0017_rice_stock_check_stock_rice_ratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rice_Sell_Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_month', models.CharField(blank=True, max_length=8, verbose_name='月份')),
                ('rice_ratio', models.CharField(blank=True, max_length=8, verbose_name='大米比例')),
                ('package_type', models.CharField(blank=True, max_length=8, verbose_name='包装')),
                ('rice_money', models.FloatField(blank=True, default=0, verbose_name='大米费用小计')),
                ('delivery_money', models.FloatField(blank=True, default=0, verbose_name='精装盒小计')),
                ('total_money', models.FloatField(blank=True, default=0, verbose_name='成本总额')),
            ],
            options={
                'verbose_name': '销售报表',
                'verbose_name_plural': '销售报表',
            },
        ),
    ]
