# Generated by Django 3.1.5 on 2021-03-09 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rice', '0019_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rice_buy_order',
            name='get_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rice.package_type'),
        ),
    ]
