# Generated by Django 3.1.5 on 2021-03-09 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rice', '0021_auto_20210309_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rice_buy_order',
            name='get_package',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='Rice.package_type', verbose_name='包装种类'),
        ),
        migrations.AlterField(
            model_name='rice_sell_order',
            name='get_package',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='Rice.package_type', verbose_name='包装种类'),
        ),
    ]
