# Generated by Django 3.1.5 on 2021-03-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rice', '0022_auto_20210309_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package_Ratio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=16, verbose_name='包装尺寸')),
            ],
            options={
                'verbose_name': '大米包装尺寸管理',
                'verbose_name_plural': '大米包装尺寸管理',
            },
        ),
    ]
