# Generated by Django 3.1.5 on 2021-03-18 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rice', '0023_package_ratio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rice_stock_check',
            name='stock_rice_ratio',
        ),
        migrations.AddField(
            model_name='rice_stock_check',
            name='get_rice_ratio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Rice.package_ratio', verbose_name='大米比例'),
        ),
        migrations.AlterField(
            model_name='rice_buy_order',
            name='get_rice_ratio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Rice.package_ratio', verbose_name='大米比例'),
        ),
        migrations.AlterField(
            model_name='rice_sell_order',
            name='get_rice_ratio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Rice.package_ratio', verbose_name='大米比例'),
        ),
    ]
