# Generated by Django 3.1.5 on 2021-04-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rice', '0024_auto_20210318_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rice_stock_check',
            name='get_rice_ratio',
            field=models.CharField(default=1, max_length=9, verbose_name='大米比例'),
        ),
    ]
