# Generated by Django 3.1.5 on 2021-04-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rice', '0025_auto_20210403_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_ratio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='包装尺寸'),
        ),
        migrations.AlterField(
            model_name='package_type',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='包装'),
        ),
    ]
